version: "3"
services:
  sharex-server:
    build: .
    ports:
      - "8484:80"
    volumes:
      - ./src/config.real.json:/usr/src/app/config.json
      - ./src/db.json:/usr/src/app/db.json
      - uploads:/var/lib/sharex-server/uploads
      - views:/var/lib/sharex-server/views
    logging:
      #limit logs to 200MB (4rotations of 50M each)
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"
    restart: unless-stopped
volumes:
  uploads:
  views:
